# Generated by Django 5.0.3 on 2024-04-16 21:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('pattern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patterns.pattern')),
                ('tempo', models.PositiveSmallIntegerField(default=130, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)])),
                ('waveform', models.CharField(choices=[('saw', 'Saw'), ('square', 'Square')], default='saw', max_length=6)),
                ('tuning', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-500), django.core.validators.MaxValueValidator(500)])),
                ('cut_off_freq', models.PositiveSmallIntegerField(default=63, validators=[django.core.validators.MaxValueValidator(127)])),
                ('resonance', models.PositiveSmallIntegerField(default=63, validators=[django.core.validators.MaxValueValidator(127)])),
                ('env_mod', models.PositiveSmallIntegerField(default=63, validators=[django.core.validators.MaxValueValidator(127)])),
                ('decay', models.PositiveSmallIntegerField(default=63, validators=[django.core.validators.MaxValueValidator(127)])),
                ('accent', models.PositiveSmallIntegerField(default=63, validators=[django.core.validators.MaxValueValidator(127)])),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='patterns.pattern')),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)])),
                ('accent', models.BooleanField(default=False)),
                ('slide', models.BooleanField(default=False)),
                ('pitch', models.PositiveSmallIntegerField(default=36, validators=[django.core.validators.MaxValueValidator(48), django.core.validators.MinValueValidator(36)])),
                ('octave', models.SmallIntegerField(choices=[(-12, 'Down'), (0, 'None'), (12, 'Up')], default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_mode', to='patterns.section')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)])),
                ('time', models.SmallIntegerField(choices=[(0, 'Rest'), (1, 'Note'), (2, 'Tied')])),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_mode', to='patterns.section')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
