# Generated by Django 5.0.3 on 2024-04-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='author',
            new_name='owner',
        ),
    ]
