# Generated by Django 5.0.3 on 2024-04-03 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('pattern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patterns.pattern')),
                ('tempo', models.PositiveSmallIntegerField(default=130, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)])),
                ('waveform', models.CharField(choices=[('saw', 'Saw'), ('square', 'Square')], default='saw', max_length=6)),
                ('tuning', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-500), django.core.validators.MaxValueValidator(500)])),
                ('cut_off_freq', models.PositiveSmallIntegerField(default=63, validators=[django.core.validators.MaxValueValidator(127)])),
                ('resonance', models.PositiveSmallIntegerField(default=63, validators=[django.core.validators.MaxValueValidator(127)])),
                ('env_mod', models.PositiveSmallIntegerField(default=63, validators=[django.core.validators.MaxValueValidator(127)])),
                ('decay', models.PositiveSmallIntegerField(default=63, validators=[django.core.validators.MaxValueValidator(127)])),
                ('accent', models.PositiveSmallIntegerField(default=63, validators=[django.core.validators.MaxValueValidator(127)])),
            ],
        ),
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
