# Generated by Django 5.0.3 on 2024-04-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_rename_author_pattern_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='owner',
            new_name='author',
        ),
    ]
