# Generated by Django 5.0.3 on 2024-04-04 22:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='patterns.pattern'),
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)])),
                ('accent', models.BooleanField(default=False)),
                ('slide', models.BooleanField(default=False)),
                ('pitch', models.PositiveSmallIntegerField(default=36, validators=[django.core.validators.MaxValueValidator(48), django.core.validators.MinValueValidator(36)])),
                ('octave', models.SmallIntegerField(choices=[(-12, 'Down'), (0, 'None'), (12, 'Up')], default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.pattern')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)])),
                ('time', models.SmallIntegerField(choices=[(0, 'Note'), (1, 'Tied'), (2, 'Rest')])),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.pattern')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
