# Generated by Django 5.0.3 on 2024-05-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_rename_owner_pattern_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='time',
            new_name='timing',
        ),
    ]
