# Generated by Django 5.0.3 on 2024-04-09 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0004_alter_section_pattern_pitch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.section'),
        ),
        migrations.AlterField(
            model_name='time',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.section'),
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.SmallIntegerField(choices=[(0, 'Rest'), (1, 'Note'), (2, 'Tied')]),
        ),
    ]
