# Generated by Django 5.0.3 on 2024-04-15 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0005_alter_pitch_section_alter_time_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_mode', to='patterns.section'),
        ),
        migrations.AlterField(
            model_name='time',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_mode', to='patterns.section'),
        ),
    ]
